trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      versionSpec: "11"
      jdkArchitectureOption: x64
      goals: 'clean test'
      options: '-Dcucumber.filter.tags="@wip"'
      testResultsFiles: '**/target/surefire-reports/*.xml'
      testRunTitle: 'Cucumber Test Results'