trigger:
  - main

pool:
  name: loupeAgent
  vmImage: ubuntu-latest

steps:
  # Step 1: Install JDK 11 using JavaToolInstaller from the Microsoft-hosted tool cache
  - task: JavaToolInstaller@0
    inputs:
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'  # Use pre-installed JDK from Microsoft-hosted agent cache

  # Step 2: Run Maven to build and test, filtering for specific Cucumber tags
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'Path'  # Use the Java path set by JavaToolInstaller
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'clean test'
      options: '-Dcucumber.filter.tags="@user"'

  # Step 3: Publish Test Results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/*.xml'
      testRunTitle: 'Cucumber Test Results'
