trigger:
- main

pool:
  name: loupeAgent
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'  # This installs Java 8
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'  # Use preinstalled JDK or provide other sources if required

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'  # Specify Java 8 here
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dcucumber.filter.tags="@user"'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/*.xml'
    testRunTitle: 'Cucumber Test Results'
