trigger:
- main  # This defines the branch that triggers the pipeline (main branch)

pool:
  name: loupeAgent
  vmImage: ubuntu-latest

steps:
- task: JavaToolInstaller@1  # Install Java 11
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: Maven@3  # Run Maven build
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Specify Java 11 here
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dcucumber.filter.tags="@user"'

- task: PublishTestResults@2  # Publish test results
  inputs:
    testResultsFiles: '**/target/surefire-reports/*.xml'
    testRunTitle: 'Cucumber Test Results'
