trigger:
- main

pool:
  name: loupeAgent
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Specify Java 11 here
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dcucumber.filter.tags="@user"'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/surefire-reports/*.xml'
    testRunTitle: 'Cucumber Test Results'
